const challenges = require('./challenges/challenges.service');
const pledgeAdmins = require('./pledgeAdmins/pledgeAdmins.service');
const events = require('./events/events.service');
const homePaymentsTransactions = require('./homePaymentsTransactions/homePaymentsTransactions.service');
const emails = require('./emails/emails.service');
const subscription = require('./subscriptions/subscription.service');
const analytics = require('./analytics/analytics.service');

const communities = require('./communities/communities.service.js');
const milestones = require('./traces/traces.service.js');
const campaigns = require('./campaigns/campaigns.service.js');
const campaigncsv = require('./csv/campaigncsv.service.js');
const users = require('./users/users.service.js');
const uploads = require('./uploads/uploads.service.js');
const donations = require('./donations/donations.service.js');
const aggregateDonations = require('./aggregateDonations/aggregateDonations.service.js');
const transactions = require('./transactions/transactions.service.js');
const whitelist = require('./whitelist/whitelist.service.js');
const gasprice = require('./gasprice/gasprice.service.js');
const verifiedCampaigns = require('./verifiedCampaigns/verifiedCampaigns.service');
const conversionRates = require('./conversionRates/conversionRates.service.js');
const conversations = require('./conversations/conversations.service.js');
const givbackReportDonations = require('./verifiedProjectsGiversReport/verifiedPerojectsGiversReport.service');
const campaignTotalDonationValue = require('./campaignTotalDonationsValue/campaignTotalDonationValue.service');

module.exports = function configure() {
  const app = this;
  app.configure(communities);
  app.configure(milestones);
  app.configure(campaigns);
  app.configure(users);
  app.configure(uploads);
  app.configure(donations);
  app.configure(aggregateDonations);
  app.configure(transactions);
  app.configure(challenges);
  app.configure(pledgeAdmins);
  app.configure(whitelist);
  app.configure(gasprice);
  app.configure(conversionRates);
  app.configure(events);
  app.configure(homePaymentsTransactions);
  app.configure(emails);
  app.configure(subscription);
  app.configure(analytics);
  app.configure(conversations);
  app.configure(campaigncsv);
  app.configure(givbackReportDonations);
  app.configure(verifiedCampaigns);
  app.configure(campaignTotalDonationValue);
};
